workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18.17.0
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.youthhandbook.app"
    scripts:
      - name: Install pnpm
        script: |
          npm install -g pnpm --force
      
      - name: Install dependencies
        script: |
          pnpm install --no-frozen-lockfile
      
      - name: Build web assets
        script: |
          export BUILD_TARGET=mobile
          pnpm run build
          node fix-paths.js
      
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      
      - name: Build iOS app (Development)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
      
      - name: Export IPA
        script: |
          cd ios/App
          mkdir -p build/ipa
          # Create unsigned IPA for testing
          cd build/App.xcarchive/Products/Applications
          mkdir Payload
          cp -r App.app Payload/
          zip -r ../../../ipa/youth-handbook-unsigned.ipa Payload
    
    artifacts:
      - ios/App/build/ipa/*.ipa
      - ios/App/build/App.xcarchive

  # Alternative: Build for simulator (easier, no signing needed)
  ios-simulator:
    name: iOS Simulator Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.17.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install pnpm
        script: |
          npm install -g pnpm
      
      - name: Install dependencies
        script: |
          pnpm install
      
      - name: Build web assets
        script: |
          export BUILD_TARGET=mobile
          pnpm run build
          node fix-paths.js
      
      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      
      - name: Build for iOS Simulator
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build
    
    artifacts:
      - ios/App/build/**/*.app
